In [1]:
import numpy as np
import sympy as sp
import random 

In [2]:
x, y, z = sp.symbols('x y z')

In [3]:
A = np.arange(1, 10).reshape(3, 3) 
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
B = np.array([[sp.sin(x)] * 3, [sp.cos(x)] * 3, [sp.tan(x)] * 3])
print(B)

[[sin(x) sin(x) sin(x)]
 [cos(x) cos(x) cos(x)]
 [tan(x) tan(x) tan(x)]]


In [5]:
C = random.randint(0, 9)
print(C)

4


In [6]:
np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
np.trace(B)

sin(x) + cos(x) + tan(x)

In [8]:
np.add(A, B)

array([[sin(x) + 1, sin(x) + 2, sin(x) + 3],
       [cos(x) + 4, cos(x) + 5, cos(x) + 6],
       [tan(x) + 7, tan(x) + 8, tan(x) + 9]], dtype=object)

In [9]:
np.dot(A, B)

array([[sin(x) + 2*cos(x) + 3*tan(x), sin(x) + 2*cos(x) + 3*tan(x),
        sin(x) + 2*cos(x) + 3*tan(x)],
       [4*sin(x) + 5*cos(x) + 6*tan(x), 4*sin(x) + 5*cos(x) + 6*tan(x),
        4*sin(x) + 5*cos(x) + 6*tan(x)],
       [7*sin(x) + 8*cos(x) + 9*tan(x), 7*sin(x) + 8*cos(x) + 9*tan(x),
        7*sin(x) + 8*cos(x) + 9*tan(x)]], dtype=object)

In [10]:
C * A

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])